{
 "title": "# Info",
 "tags": [ "factorio" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "TimeScale",
    "label": "TimeScale",
    "query": "Second : 1, Minute : 60, Hour : 3600"
   },
   {
    "name": "Force",
    "label": "Force",
    "query": {
     "query": "label_values({__name__=~\"factorio_evolution|factorio_research_queue|factorio_items_launched\"},force)"
    }
   },
   {
    "name": "helper_research_name",
    "label": "helper_research_name",
    "query": {
     "query": "query_result(factorio_research_queue{index=\"1\"})"
    }
   },
   {
    "name": "helper_research_level",
    "label": "helper_research_level",
    "query": {
     "query": "label_values(factorio_research_queue{index=\"1\",name=\"${helper_research_name}\"},level)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "last ${TimeScale}",
     "type": "stat",
     "description": "In Game UPS [Updates Per Second]",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "UPS" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "round(rate(factorio_tick[${TimeScale}s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UPS",
     "type": "timeseries",
     "description": "In Game UPS [Updates Per Second]",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 7 },
     "targets": [
      {
       "expr": "rate(factorio_tick[$__rate_interval])",
       "legendFormat": "UPS"
      }
     ]
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Game Time",
   "type": "stat",
   "description": "Age of the save game",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "factorio_tick / 60" }
   ]
  },
  {
   "title": "Player",
   "type": "stat",
   "description": "Overall Player Count",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "factorio_total_player_count" }
   ]
  },
  {
   "title": "Player Online",
   "type": "stat",
   "description": "Current Player Count",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_connected_player_count"
    }
   ]
  },
  {
   "title": "Factorio",
   "type": "stat",
   "description": "Factorio Version",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_mods{name=\"base\"}==1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mods",
   "type": "table",
   "description": "Installed mod and its version",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "expr": "factorio_mods{name!=\"base\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seed",
   "type": "stat",
   "description": "Map Seed",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "factorio_seed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evolution",
   "type": "stat",
   "description": "Current Evolution Level",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_evolution{force=~\"${Force}\",type=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evolution Composition",
   "type": "stat",
   "description": "Composition of current evolution level",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_evolution{force=~\"${Force}\",type!=\"total\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(factorio_evolution{force=~\"${Force}\",type!=\"total\"})",
     "legendFormat": "sum"
    }
   ]
  },
  { "title": "Research", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Research ETA",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  min_over_time(\r\n    (\r\n        timestamp(\r\n          factorio_research_queue{force=~\"${Force}\",index=\"1\",level=\"${helper_research_level}\",name=\"${helper_research_name}\"}\r\n        )\r\n      and\r\n        (\r\n            factorio_research_queue{force=~\"${Force}\",index=\"1\",level=\"${helper_research_level}\",name=\"${helper_research_name}\"}\r\n          ==\r\n            scalar(\r\n              max_over_time(\r\n                factorio_research_queue{force=~\"${Force}\",index=\"1\",level=\"${helper_research_level}\",name=\"${helper_research_name}\"}[2w]\r\n              )\r\n            )\r\n        )\r\n    )[1w:]\r\n  )\r\n*\r\n  1000",
     "legendFormat": "start"
    },
    {
     "expr": "timestamp(factorio_research_queue{force=~\"${Force}\",index=\"1\"}) * 1000",
     "legendFormat": "current"
    },
    {
     "expr": "factorio_research_queue{force=~\"${Force}\",index=\"1\"}",
     "legendFormat": "progress"
    }
   ]
  },
  {
   "title": "Current Research",
   "type": "table",
   "description": "Current research and its level",
   "gridPos": { "h": 2, "w": 11, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "factorio_research_queue{force=~\"${Force}\",index=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Research Queue",
   "type": "table",
   "description": "Current research queue and its level",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "factorio_research_queue{force=~\"${Force}\",index!=\"1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Research Progress",
   "type": "stat",
   "description": "Progress of currently running research",
   "gridPos": { "h": 5, "w": 11, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_research_queue{force=~\"${Force}\",index=\"1\",level=\"${helper_research_level}\",name=\"${helper_research_name}\"}",
     "legendFormat": "__auto",
     "target": "randomWalk('myName')"
    }
   ]
  },
  { "title": "Rockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Rockets Launched",
   "type": "stat",
   "description": "Overall rockets launched incl. all cargo types",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "factorio_items_launched{name=\"satellite\"} or on() vector(0)",
     "legendFormat": "__auto",
     "target": "randomWalk('myName')"
    }
   ]
  },
  {
   "title": "Satellite Rockets Per ${TimeScale}",
   "type": "stat",
   "description": "Average of launched satellite rockets in ${TimeScale} seconds based on launched satellite rockets within the last hour",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(factorio_items_launched{name=\"satellite\"}[1h]) * ${TimeScale} or on() vector(0)",
     "legendFormat": "__auto",
     "target": "randomWalk('myName')"
    }
   ]
  }
 ]
}