#!/usr/bin/env python3
"""Regenerate .luacheckrc by running luacheck with an API-only config and
declaring every reported mod-level global. Keeps the config and the code
in lockstep; run after adding cross-module symbols."""
import subprocess, sys, re, pathlib, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
API = ["commands","data","defines","game","helpers","localised_print","log","mods",
       "prototypes","rcon","remote","rendering","script","serpent","settings","table_size","util"]

minimal = 'std = "lua52"\nread_globals = {' + ",".join(f'"{a}"' for a in API) + '}\n' \
          'globals = { storage = { other_fields = true } }\n' \
          'exclude_files = { "prometheus/**", "dist/**", "node_modules/**" }\nmax_line_length = false\n'
tmp = ROOT / ".luacheckrc.gen"
tmp.write_text(minimal, encoding="utf-8")
res = subprocess.run(["luacheck", ".", "--config", str(tmp), "--formatter", "plain"],
                     cwd=ROOT, capture_output=True, text=True)
tmp.unlink()
names = sorted(set(re.findall(r"(?:setting non-standard global variable|accessing undefined variable) '([A-Za-z_][A-Za-z0-9_]*)'", res.stdout)))
out  = "-- Luacheck configuration for graftorio3 -- generated by scripts/gen_luacheckrc.py\n"
out += "-- read_globals: Factorio runtime API; globals: this mod's cross-module symbols\n\n"
out += 'std = "lua52"\ncache = true\n\n'
out += "read_globals = {\n" + "".join(f'  "{n}",\n' for n in API) + "}\n\n"
out += "globals = {\n  storage = { other_fields = true },\n"
out += "".join(f'  "{n}",\n' for n in names) + "}\n\n"
out += 'exclude_files = { "prometheus/**", "dist/**", "node_modules/**" }\n\nmax_line_length = false\n'
(ROOT / ".luacheckrc").write_text(out, encoding="utf-8")
print(f".luacheckrc generiert: {len(names)} Mod-Globals")
